name: hello_world
description: "A new Flutter project."
publish_to: 'none' # Verhindert versehentliches Veröffentlichen auf pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  fl_chart: ^0.64.0
  window_size: ^0.1.0 # nur für Windows/macOS/Linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logo HOT GMBH.png