name: hello_world
description: "A new Flutter project."
publish_to: 'none' # Verhindert Veröffentlichung auf pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  fl_chart: ^0.64.0
  window_size: ^0.1.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  geocoding: ^2.2.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/Logo HOT GMBH.png